<a href="https://colab.research.google.com/github/HiveCase/DA4001-AI/blob/main/Assignments/Week2/Week2_Q6to10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
df = pd.read_csv('week_2_dataset.csv')
df.sample(5)

,house_type,room_count,house_size,location,city,latitude,longitude,num_bathrooms,num_balconies,security_deposit,status,price
406,Apartment,3 BHK,1560.0,Andheri West,Mumbai,19.143885,72.824509,3.0,0.0,0,Furnished,160000
3080,Apartment,1 BHK,700.0,Dombivali,Mumbai,19.227549,73.081505,2.0,0.0,0,Unfurnished,9500
3529,Apartment,2 BHK,900.0,Thane West,Mumbai,19.225767,72.994225,2.0,0.0,0,Semi-Furnished,30000
2241,Independent Floor,3 BHK,2856.0,Saket,Delhi,28.523548,77.200142,3.0,2.0,>100k,Unfurnished,301012
3938,Apartment,3 BHK,1500.0,Powai,Mumbai,19.118999,72.917191,NaN,0.0,0,Semi-Furnished,90000

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   house_type        3491 non-null   object
 1   room_count        4000 non-null   object
 2   house_size        3772 non-null   float64
 3   location          4000 non-null   object
 4   city              4000 non-null   object
 5   latitude          4000 non-null   float64
 6   longitude         4000 non-null   float64
 7   num_bathrooms     3643 non-null   float64
 8   num_balconies     4000 non-null   float64
 9   security_deposit  3713 non-null   object
 10  status            4000 non-null   object
 11  price             4000 non-null   int64
dtypes: float64(5), int64(1), object(6)
memory usage: 375.1+ KB

In [37]:
df.isna().sum()

house_type          509
room_count            0
house_size          228
location              0
city                  0
latitude              0
longitude             0
num_bathrooms       357
num_balconies         0
security_deposit    287
status                0
price                 0
dtype: int64

In [38]:
X = df.drop(columns=['price'])
X.head()

,house_type,room_count,house_size,location,city,latitude,longitude,num_bathrooms,num_balconies,security_deposit,status
0,Apartment,2 BHK,1250.0,Balewadi,Pune,18.574335,73.772736,2.0,2.0,<=100k,Semi-Furnished
1,Independent Floor,3 BHK,2000.0,Greater Kailash,Delhi,28.544849,77.242538,3.0,0.0,NaN,Semi-Furnished
2,Villa,4 BHK,5896.0,Navjeevan Vihar,Delhi,28.533476,77.199554,4.0,2.0,>100k,Unfurnished
3,Apartment,1 BHK,650.0,Dombivali,Mumbai,19.208801,73.096649,2.0,0.0,0,Semi-Furnished
4,Apartment,2 BHK,900.0,Dadar East,Mumbai,19.014477,72.845497,NaN,0.0,NaN,Furnished

In [39]:
y = df['price']
y

0        25000
1       150000
2       401105
3        15000
4        60000
         ...
3995    301012
3996    301011
3997      4000
3998    381022
3999     26000
Name: price, Length: 4000, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
preprocessor = ColumnTransformer(
    transformers=[
        ("bath", SimpleImputer(strategy="median"), ["num_bathrooms"]),
        ("house_size", SimpleImputer(strategy="mean"),["house_size"]),
        ("house_type", SimpleImputer(strategy="most_frequent"),["house_type"]),
        ("security_deposit", SimpleImputer(strategy="constant", fill_value="unknown"),["security_deposit"])
    ], remainder="passthrough",
    verbose_feature_names_out=False
).set_output(transform="pandas")

In [44]:
X_train_processed = preprocessor.fit_transform(X_train)
X_train_processed.sample(4)

,num_bathrooms,house_size,house_type,security_deposit,room_count,location,city,latitude,longitude,num_balconies,status
3603,2.0,620.0,Apartment,0,1 BHK,Virar West,Mumbai,19.452856,72.801659,0.0,Semi-Furnished
336,3.0,1800.0,Apartment,0,3 BHK,Chembur,Mumbai,19.054434,72.900360,0.0,Semi-Furnished
1508,3.0,1600.0,Independent Floor,0,3 BHK,Paschim Vihar,Delhi,28.657253,77.091988,0.0,Semi-Furnished
699,2.0,1025.0,Apartment,0,2 BHK,Kharadi,Pune,18.562901,73.949081,0.0,Semi-Furnished

In [45]:
X_test_processed = preprocessor.transform(X_test)
X_test_processed.sample(4)

,num_bathrooms,house_size,house_type,security_deposit,room_count,location,city,latitude,longitude,num_balconies,status
1377,4.0,2500.0,Apartment,>100k,4 BHK,Saket,Delhi,28.517656,77.204330,3.0,Furnished
3317,2.0,900.0,Apartment,0,2 BHK,Dahisar,Mumbai,19.261669,72.874306,0.0,Semi-Furnished
1448,2.0,820.0,Apartment,0,2 BHK,Bandra West,Mumbai,19.059561,72.829529,0.0,Semi-Furnished
3078,2.0,900.0,Apartment,<=100k,2 BHK,Sheikh Sarai,Delhi,28.534279,77.208412,3.0,Semi-Furnished

In [46]:
X_test_processed["house_size"].mean()

np.float64(1776.2241116352202)

In [47]:
np.mean(X_test["house_size"])

np.float64(1774.6231691078563)

In [48]:
print(f"The mean value of house_size after imputation is: {round(X_test_processed["house_size"].mean(),2)}")

The mean value of house_size after imputation is: 1776.22

In [49]:
X_train.isna().sum()

house_type          414
room_count            0
house_size          179
location              0
city                  0
latitude              0
longitude             0
num_bathrooms       287
num_balconies         0
security_deposit    231
status                0
dtype: int64

In [50]:
X_train_processed.isna().sum()

num_bathrooms       0
house_size          0
house_type          0
security_deposit    0
room_count          0
location            0
city                0
latitude            0
longitude           0
num_balconies       0
status              0
dtype: int64

In [51]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, MinMaxScaler
from sklearn.pipeline import Pipeline

In [54]:
encoder = ColumnTransformer(
    transformers=[
        ("ordinal", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=1000), ["room_count","house_type","location"]),
        ("onehot", OneHotEncoder(sparse_output=False,drop='first'), ["city", "status", "security_deposit"])
    ],
    remainder="passthrough",
    verbose_feature_names_out=False
).set_output(transform="pandas")

In [55]:
pipe = Pipeline([
    ("imputer", preprocessor),
    ("encoder", encoder),
    ("scaler", MinMaxScaler())
])

In [56]:
X_train_final = pipe.fit_transform(X_train)
X_test_final = pipe.transform(X_test)

In [57]:
X_test_final[:100].sum()

np.float64(408.37086925773906)

In [58]:
print(f"The sum of first 100 rows of data in Transformed Test dataset: {round(X_test_final[:100].sum(),2)}")

The sum of first 100 rows of data in Transformed Test dataset: 408.37

In [59]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [60]:
rfe_pipe = Pipeline([
    ("rfe", RFE(estimator=LinearRegression(), n_features_to_select=10)),
    ("knn", KNeighborsRegressor(n_neighbors=10))
])

In [70]:
rfe_pipe.fit(X_train_last,y_train)

Pipeline(steps=[('rfe',
                 RFE(estimator=LinearRegression(), n_features_to_select=10)),
                ('knn', KNeighborsRegressor(n_neighbors=10))])

In [71]:
rfe = rfe_pipe.named_steps["rfe"]
rfe

RFE(estimator=LinearRegression(), n_features_to_select=10)

In [65]:
X_train_final

array([[0.375     , 0.        , 0.60856269, ..., 0.04234615, 0.08218982,
        0.        ],
       [0.375     , 0.        , 0.3853211 , ..., 0.0497952 , 0.06750712,
        0.        ],
       [0.375     , 0.2       , 0.82262997, ..., 0.81463384, 0.96359789,
        0.33333333],
       ...,
       [0.25      , 0.        , 0.65443425, ..., 0.81297511, 0.98118883,
        0.        ],
       [0.        , 0.        , 0.40061162, ..., 0.05481484, 0.0540047 ,
        0.        ],
       [0.25      , 0.        , 0.35168196, ..., 0.05714294, 0.03887086,
        0.        ]])

In [67]:
pipe.set_output(transform="pandas")

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('imputer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('bath',
                                                  SimpleImputer(strategy='median'),
                                                  ['num_bathrooms']),
                                                 ('house_size', SimpleImputer(),
                                                  ['house_size']),
                                                 ('house_type',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  ['house_type']),
                                                 ('security_deposit',
                                                  SimpleImputer(fill_value='unknown',
                                                                strategy='constant'),
                                                  ['security_depo...
                                   verbose_feature_names_out=False)),
                ('encoder',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinal',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=1000),
                                                  ['room_count', 'house_type',
                                                   'location']),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['city', 'status',
                                                   'security_deposit'])],
                                   verbose_feature_names_out=False)),
                ('scaler', MinMaxScaler())])

In [68]:
X_train_last = pipe.fit_transform(X_train)

In [73]:
idx = X_train_last.columns.get_loc("location")
rfe.ranking_[idx]

np.int64(4)

In [87]:
from sklearn.metrics import r2_score, root_mean_squared_error

In [76]:
y_pred = rfe_pipe.predict(X_test_final)
r2 = r2_score(y_test, y_pred)
r2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

0.685141595340768

In [80]:
from sklearn.decomposition import PCA
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV

In [81]:
pca = Pipeline([
    ("pca", PCA()),
    ("svr", SVR())
])

In [82]:
param_grid = {
    "pca__n_components": [0.9, 0.95],
    "svr__kernel": ["linear", "poly", "rbf"]
}

In [83]:
grid = GridSearchCV(estimator=pca,
                    param_grid=param_grid,
                    scoring="neg_mean_absolute_error",
                    cv=5,
                    n_jobs=-1)

In [84]:
grid.fit(X_train_final, y_train)

GridSearchCV(cv=5, estimator=Pipeline(steps=[('pca', PCA()), ('svr', SVR())]),
             n_jobs=-1,
             param_grid={'pca__n_components': [0.9, 0.95],
                         'svr__kernel': ['linear', 'poly', 'rbf']},
             scoring='neg_mean_absolute_error')

In [85]:
y_pred = grid.predict(X_test_final)

In [89]:
rmse = root_mean_squared_error(y_pred,y_test)
rmse

207188.13714567534

In [90]:
print(f"The RMSE using PCA & SVR is: {round(rmse,2)}")

The RMSE using PCA & SVR is: 207188.14